# Server
server.port=8080

# Application
spring.application.name=api-gateway

# Gateway Discovery Locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===================== ROUTES =====================

# Patient Service
#spring.cloud.gateway.routes[0].id=patient-service
#spring.cloud.gateway.routes[0].uri=lb://patient-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**,/api/appointments/**,/api/doctors/**
#spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

# Triage Service
#spring.cloud.gateway.routes[1].id=triage-service
#spring.cloud.gateway.routes[1].uri=lb://triage-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/triage/**
#spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# Notification Service
#spring.cloud.gateway.routes[2].id=notification-service
#spring.cloud.gateway.routes[2].uri=lb://notification-service
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notifications/**
#spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# ===================== EUREKA =====================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===================== ACTUATOR =====================
management.endpoints.web.exposure.include=health,info,gateway

# Tracing
#management.tracing.sampling.probability=1.0
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# ===================== JWT =====================
jwt.secret=mediqueue-secret-key-must-be-at-least-256-bits-long-for-hs256