package com.mediqueue.notification.events;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Event published when triage analysis is completed for an appointment.
 * <p>
 * This event is typically produced after evaluating patient symptoms,
 * possibly using an AI service, and is consumed by downstream services
 * such as notification-service or queue-management to take further actions.
 * </p>
 *
 * <p>
 * This DTO represents a Kafka message payload and should remain backward-compatible
 * to avoid breaking existing consumers.
 * </p>
 */
@Getter
@AllArgsConstructor
public class TriageCompletedEvent {

    /**
     * Unique identifier of the appointment associated with this triage result.
     * <p>
     * Used for correlation across services and idempotency handling.
     * </p>
     */
    private String appointmentId;

    /**
     * Unique identifier of the patient.
     */
    private String patientId;

    /**
     * Priority level assigned after triage.
     * <p>
     * Example values: HIGH, MEDIUM, LOW.
     * Used for queue prioritization and downstream processing.
     * </p>
     */
    private String priority;

    /**
     * Explanation or reasoning behind the assigned priority.
     * <p>
     * Typically generated by an AI model or triage logic for transparency
     * and debugging purposes.
     * </p>
     */
    private String reasoning;

    /**
     * Indicates whether AI-based triage was successfully performed.
     * <p>
     * If false, downstream services may skip certain actions
     * or fall back to default behavior.
     * </p>
     */
    private boolean aiAvailable;
}
