# Server
server.port=8761

# Spring
spring.application.name=eureka-server

# Eureka Instance
eureka.instance.hostname=localhost

# Eureka Client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Eureka Server
eureka.server.wait-time-in-ms-when-sync-empty=0

# Actuator (Management)
management.endpoints.web.exposure.include=health,info