# Server
server.port=8761

# Spring
spring.application.name=eureka-server

# Eureka Instance
eureka.instance.hostname=localhost

# Eureka Client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Eureka Server
eureka.server.wait-time-in-ms-when-sync-empty=0

# Actuator (Management)
management.endpoints.web.exposure.include=health,info

# --- FOR LOCAL DEVELOPMENT ---

# Disable self-preservation to stop the "Emergency" warning
eureka.server.enable-self-preservation=false

# How often the server scans for dead instances (in ms)
# This clears out old ports so your Gateway doesn't get a 404
eureka.server.eviction-interval-timer-in-ms=2000